In this notebook you are defining a contact map for critical regions involved in unbinding. These are contacts between the protein and the DNA as well as contacts in the hinge region.

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import mdtraj as md

First you load two topologies of the protein-DNA system. One (topo_ref) will not contain the bases of the DNA because it is used to analyse the combined trajectories from unbinding using NMR restraints with DNA of a specific (OSymL) and a nonspecific (NOD) sequence.

# Make sure to choose the correct in and output paths for the sequence you want to prepare input files for!

In [60]:
folder = "/home/x_mallu/mln_lf/Transcriptionfactor_unbinding/PLUMED_input/"
#folder_out = "/home/x_mallu/mln_lf/Transcriptionfactor_unbinding/PLUMED_input/cmaps/OSymL/"
folder_out = "/home/x_mallu/mln_lf/Transcriptionfactor_unbinding/PLUMED_input/cmaps/NOD/"

#topo = md.load_pdb(folder + "pdbs_plumed_numbering/OSymL/1efa_noTet_99sbws_proc_mod_resID.pdb")
topo = md.load_pdb(folder + "pdbs_plumed_numbering/NOD/1efa_NOD_S99_mod_ID.pdb")

Get the DNA backbone and base identifiers:

In [14]:
DNA_bb = topo.topology.select(\
    """(name =~ "C1\'") or (name =~ "C2\'") or (name =~ "C3\'") or (name =~ "C4\'") or (name =~ "C5\'") or 
    (name =~ "O1\'") or (name =~ "O2\'") or (name =~ "O3\'") or (name =~ "O4\'") or (name =~ "O5\'")  
    or (name P) or (name =~ 'O*P')""" )
print("Number if DNA backbone atoms", len(DNA_bb ))

Number if DNA backbone atoms 518

In [15]:
DNA_bases = topo.topology.select(\
    """(name N1) or (name N3) or (name C2) or (name C4) or (name C5) or (name C6) or (name C8) or
    (name N6) or (name N4) or (name N7) or (name N9) or (name O6)  
    or (name O4) or (name O2)""" )
print("Number if DNA base atoms", len(DNA_bases ))

Number if DNA base atoms 432

In [16]:
spec_residues_ids = [6,7,17,18,21,22,29] #IDs according to LacI sequence
hinge_residues_ids = [51,52,53,54,55,56,57] #IDs according to LacI sequence

In [17]:
def get_spec_residues_python_heavy(res_list, start=2, chainB=None):
    """Function that writes out a string specifying residues with python numbering.
    
    Parameters
    ----------
    res_list: list
        list with residue IDs according to seqeuence.
    start: int
        by what the numbering needs to be moved for fhe python residue number.
    chainB: int
        number of residues in chain A by which the residue indexes have to be 
        increased to obtain residue IDs for chain B.
        
    Returns
    -------
    specific_residues: str
        string that identifies the residues in res_list in python numbering (mdtraj), only heavy atoms!"""
    
    if chainB:
        res_list_chainB = [spec_residues_id + chainB for spec_residues_id in res_list]
        res_list_dimer = res_list + res_list_chainB
        specific_residues_list = [x - start for x in res_list_dimer]
    else:
        specific_residues_list = [x - start for x in res_list]
    
    specific_residues = "(resid {} or ".format(specific_residues_list[0])
    for i in range(len(specific_residues_list)-2):
        specific_residues = specific_residues + "resid {} or ".format(specific_residues_list[i+1])
    specific_residues = specific_residues + "resid {}) and mass >= 2".format(specific_residues_list[-1])
    return(specific_residues)

In [18]:
selection_specific = get_spec_residues_python_heavy(spec_residues_ids,chainB=335)
selection_hinges = get_spec_residues_python_heavy(hinge_residues_ids,chainB=335)

In [19]:
spec_residues_ids

[6, 7, 17, 18, 21, 22, 29]

In [20]:
selection_specific

'(resid 4 or resid 5 or resid 15 or resid 16 or resid 19 or resid 20 or resid 27 or resid 339 or resid 340 or resid 350 or resid 351 or resid 354 or resid 355 or resid 362) and mass >= 2'

In [21]:
specific = topo.top.select(selection_specific) # specifically interacting side chains of LacI
[atom.residue for atom in topo.top.atoms if atom.index in specific]

[LEU5,
 LEU5,
 LEU5,
 LEU5,
 LEU5,
 LEU5,
 LEU5,
 LEU5,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR6,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 TYR16,
 GLN17,
 GLN17,
 GLN17,
 GLN17,
 GLN17,
 GLN17,
 GLN17,
 GLN17,
 GLN17,
 SER20,
 SER20,
 SER20,
 SER20,
 SER20,
 SER20,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 ARG21,
 HIS28,
 HIS28,
 HIS28,
 HIS28,
 HIS28,
 HIS28,
 HIS28,
 HIS28,
 HIS28,
 HIS28,
 LEU340,
 LEU340,
 LEU340,
 LEU340,
 LEU340,
 LEU340,
 LEU340,
 LEU340,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR341,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 TYR351,
 GLN352,
 GLN352,
 GLN352,
 GLN352,
 GLN352,
 GLN352,
 GLN352,
 GLN352,
 GLN352,
 SER355,
 SER355,
 SER355,
 SER355,
 SER355,
 SER355,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 ARG356,
 HIS363,
 HIS363,
 HIS363,
 HIS363,
 HIS363,
 HIS363,
 HIS363,
 HIS363,
 HIS363,
 HIS363]

In [22]:
hinges = topo.top.select(selection_hinges) # hinge atoms
[atom.residue for atom in topo.top.atoms if atom.index in hinges]

[ARG50,
 ARG50,
 ARG50,
 ARG50,
 ARG50,
 ARG50,
 ARG50,
 ARG50,
 ARG50,
 ARG50,
 ARG50,
 VAL51,
 VAL51,
 VAL51,
 VAL51,
 VAL51,
 VAL51,
 VAL51,
 ALA52,
 ALA52,
 ALA52,
 ALA52,
 ALA52,
 GLN53,
 GLN53,
 GLN53,
 GLN53,
 GLN53,
 GLN53,
 GLN53,
 GLN53,
 GLN53,
 GLN54,
 GLN54,
 GLN54,
 GLN54,
 GLN54,
 GLN54,
 GLN54,
 GLN54,
 GLN54,
 LEU55,
 LEU55,
 LEU55,
 LEU55,
 LEU55,
 LEU55,
 LEU55,
 LEU55,
 ALA56,
 ALA56,
 ALA56,
 ALA56,
 ALA56,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 ARG385,
 VAL386,
 VAL386,
 VAL386,
 VAL386,
 VAL386,
 VAL386,
 VAL386,
 ALA387,
 ALA387,
 ALA387,
 ALA387,
 ALA387,
 GLN388,
 GLN388,
 GLN388,
 GLN388,
 GLN388,
 GLN388,
 GLN388,
 GLN388,
 GLN388,
 GLN389,
 GLN389,
 GLN389,
 GLN389,
 GLN389,
 GLN389,
 GLN389,
 GLN389,
 GLN389,
 LEU390,
 LEU390,
 LEU390,
 LEU390,
 LEU390,
 LEU390,
 LEU390,
 LEU390,
 ALA391,
 ALA391,
 ALA391,
 ALA391,
 ALA391]

Get the pair list between specifically interacting residues and the DNA.

In [23]:
def paired_list(list1,list2):
    """Get the list of all pairs between memeber of list1 and list2.
    
    Parameters
    ----------
    
    list1: list
        list of atoms and residues extracted with mdtraj.
    list2: list
        list of atoms and residues extracted with mdtraj."""
    
    paired_list = []
    for x in list1:
        for y in list2:
            paired_list.append([x,y])  
    return(paired_list)

In [24]:
spec_DNA_bb = paired_list( specific, DNA_bb ) #this will give you atom pairs
distances_spec_DNA_bb = md.compute_distances(topo, spec_DNA_bb ) #this will give you the distances of the atom pairs


spec_DNA_bases = paired_list( specific, DNA_bases )
distances_spec_DNA_bases = md.compute_distances(topo, spec_DNA_bases )

Get the distance between atom pairs in the hinge region.

In [25]:
hinge_hinge = paired_list( hinges[:int(len(hinges)/2)], hinges[int(len(hinges)/2):])
distances_hinge_hinge = md.compute_distances(topo, hinge_hinge ) #this will give you atom pairs
len( hinge_hinge )

2916

In [26]:
def shortest_distances(pairs, distances, topology):
    """ Compute the shortest distance between two residues.
    
    Parameters
    ----------
    pairs: list
        atom pairs 
    distances: list
        distances between atom pairs
    Returns
    -------
    df_shortest_distances: pandas DataFrame
        contains the closest atom pairs between two sets of residues and their atom ids, the residue ID 
        of the protein residue and their distance.
    """
    
    listA = np.unique([x[0] for x in pairs])
    ref_df = pd.DataFrame( \
            { "pairA": [x[0] for x in pairs], "pairB": [x[1] for x in pairs], "dist" :  distances[0] } ) 
    shortest_distances = []
    for i in listA:
        # find the shortest distance
        shortest_dist = ref_df[ref_df["pairA"] == i ]
        shortest_distances.append( shortest_dist[ shortest_dist['dist']==shortest_dist['dist'].min() ] )
    df_shortest_distances = pd.concat([i for i in shortest_distances])
    #now you have one closest partner for all atoms of interaction partner A
    
    residues = [atom.residue.index for atom in topology.top.atoms if atom.index in \
                      list(df_shortest_distances["pairA"])] 
    residue_list = np.unique( residues )
    df_shortest_distances["residID"] = residues
    
    shortest_distances = []
    for i in residue_list:
        # find the shortest distance
        shortest_dist = df_shortest_distances[df_shortest_distances["residID"] == i ]
        shortest_distances.append( shortest_dist[ shortest_dist['dist']==shortest_dist['dist'].min() ] )
    df_shortest_distances = pd.concat([i for i in shortest_distances])
    return(df_shortest_distances)

In [27]:
df_shortest_distances_protein_DNA_bb = shortest_distances( spec_DNA_bb, distances_spec_DNA_bb, topo)
df_shortest_distances_protein_DNA_bases = shortest_distances( spec_DNA_bases, distances_spec_DNA_bases, topo)
df_shortest_distances_hinges = shortest_distances(hinge_hinge, distances_hinge_hinge, topo)

In [28]:
df_shortest_distances_protein_DNA_bb

       pairA  pairB      dist  residID
1178      72  10584  0.292798        4
4286      87  10584  0.485588        5
16211    246  10614  0.555166       15
19319    258  10614  0.556551       16
22945    301  10614  0.251668       19
26731    315  11087  0.530784       20
32418    421  11055  0.322905       27
36661   5157  11345  0.263603      339
39769   5172  11345  0.477672      340
51694   5331  11375  0.560338      350
54802   5343  11375  0.529490      351
58428   5386  11375  0.251901      354
63257   5406  10352  0.477238      355
67383   5506  10294  0.386362      362

In [29]:
df_shortest_distances_protein_DNA_bases

       pairA  pairB      dist  residID
2279      81  10595  0.521387        4
6602     100  10600  0.357420        5
11952    239  11197  0.314544       15
16554    259  10662  0.272397       16
19135    301  10625  0.465383       19
24033    324  11135  0.299651       20
26174    417  11068  0.436597       27
31871   5166  11356  0.492268      339
36194   5185  11361  0.319423      340
41115   5324  10439  0.287918      350
46146   5344  11423  0.269604      351
48728   5386  11388  0.469636      354
53190   5409  10371  0.291428      355
58366   5515  10339  0.495465      362

In [30]:
df_shortest_distances_hinges

      pairA  pairB      dist  residID
554     782   5874  0.531114       49
932     798   5874  0.308723       50
1125    803   5937  0.380669       51
1634    824   5874  0.634579       52
2013    837   5878  0.299966       53
2530    856   5941  0.328736       54
2692    862   5941  0.633479       55

In [57]:
def write_pymol_script(native_contacts,name="pymol.txt"):
    """Function that formats pymol script.
    
    Parameters
    ----------
    native_contatcs: list
        contains the contact that you want to include in the CV
    name: string
        name of the script
    Writes
    ------
    file: file
        pymol.txt pymol script. Run in pymol with @pymol.txt
    """
    file = open(folder_out + "/{}".format(name), "w")
    file.write("")
    for m in range( len( native_contacts )):
        i, j = int(native_contacts.iloc[m]["pairA"]), int(native_contacts.iloc[m]["pairB"])

        file.write("sele pk{m}, id {i} or id {j}\n"\
                   .format(i=i+1,j=j+1,m=m+1))


    file.close()

In [64]:
write_pymol_script(df_shortest_distances_protein_DNA_bases)

In [59]:
pairs_binding = pd.concat([df_shortest_distances_protein_DNA_bases,df_shortest_distances_hinges])

In [47]:
pairs_binding

       pairA  pairB      dist  residID
2279      81  10595  0.521387        4
6602     100  10600  0.357420        5
11952    239  11197  0.314544       15
16554    259  10662  0.272397       16
19135    301  10625  0.465383       19
24033    324  11135  0.299651       20
26174    417  11068  0.436597       27
31871   5166  11356  0.492268      339
36194   5185  11361  0.319423      340
41115   5324  10439  0.287918      350
46146   5344  11423  0.269604      351
48728   5386  11388  0.469636      354
53190   5409  10371  0.291428      355
58366   5515  10339  0.495465      362
554      782   5874  0.531114       49
932      798   5874  0.308723       50
1125     803   5937  0.380669       51
1634     824   5874  0.634579       52
2013     837   5878  0.299966       53
2530     856   5941  0.328736       54
2692     862   5941  0.633479       55

In [61]:
def write_plumed_input_rational_d0(native_contacts, reference_distances,name="NMR"):
    """Function that formats plumed based input contacts for rational switch with d0 != 0.
    
    Parameters
    ----------
    native_contatcs: list
        contains the contact that you want to include in the CV
    reference_distances: list
        distances between the contact partners in the reference/starting structure.
    Writes
    ------
    file: txt file
        plumed contact map
    """
    
    file = open(folder_out + "/cmap_rat_{}.txt".format(name), "w")
    file.write("CONTACTMAP ...\n")
    for m in range( len( native_contacts )):
        i, j = native_contacts[m]
        file.write("ATOMS{m}={i},{j} SWITCH{m}={{RATIONAL R_0=0.3 D_0={dist:.4f} }}\n"\
                   .format(i=i+1,j=j+1,m=m+1, dist = reference_distances[m]))
    file.write("LABEL=cmap\n")
    file.write("SUM\n")
    file.write("... CONTACTMAP\n")
    file.close()

In [62]:
write_plumed_input_rational_d0( \
[[x,y] for x,y in zip(list(df_shortest_distances_protein_DNA_bases['pairA']),list(df_shortest_distances_protein_DNA_bases['pairB']))]\
                            ,list(df_shortest_distances_protein_DNA_bases['dist']), name="specific_protein_DNA")

In [63]:
write_plumed_input_rational_d0( \
[[x,y] for x,y in zip(list(pairs_binding['pairA']),list(pairs_binding['pairB']))]\
                            ,list(pairs_binding['dist']), name="specific_protein_DNA_plus_protein_protein")